### ISSUE TITLE
Relay terminals inverted

### ISSUE THREAD

**Issue by iwill80** [piface/pifacedigital-emulator#4]
Hi guys,
I found a bug in pifacedigital-emulator. When I enable output 1 (relay K1) the terminals of the relay K0 change their status and viceversa.
See the attcahed image

![pifacedigital-emulator](https://cloud.githubusercontent.com/assets/8006253/3423267/bf163a48-ff8b-11e3-8d51-26eb50f07f2e.png)

**Comment by tompreston** [comment]
Whoops, that's an obvious one! Fixed in v2.0.3.
